name: Acceptance Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-acceptance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Create CI-Optimized Config
        run: |
          mkdir -p examples/configs
          cat <<'EOF' > examples/configs/ci_config.yaml
          seed: 1337
          fs: 1000
          duration_s: 20
          window_s: 0.4
          hop_s: 0.2
          cv_folds: 3
          latency_budget_ms: 2000.0
          use_wavelets: true
          wavelet_family: "db4"
          wavelet_level: 4
          use_hilbert_phase: true
          coherence_subbands:
            - [1, 40]
            - [40, 100]
          target:
            ehi_weights: { thd: 0.45, ipr: 0.55 }
          gbdt_params:
            n_estimators: 10
            max_depth: 3
          fftboost:
            atoms: 5
            lambda_hf: 0.10
            lambda_coh: 3.0
            min_sep_bins: 3
            ridge_alpha: 0.1
          EOF

      - name: Run evaluation via CLI
        run: fftboost --config examples/configs/ci_config.yaml --save-telemetry telemetry.json

      - name: Check acceptance gates
        run: |
          python -c "
          import json, sys
          with open('telemetry.json', 'r') as f:
              data = json.load(f)

          gates = data.get('acceptance', {})
          j_beats_passed = gates.get('j_beats_pass', False)

          print(f'J_beats Gate Passed: {j_beats_passed}')
          if not j_beats_passed:
              print('ERROR: J_beats acceptance gate failed!')
              sys.exit(1)

          print('SUCCESS: All acceptance gates passed.')
          "
