name: Notebook Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Execute quickstart notebook
        run: |
          jupyter nbconvert --to notebook --execute examples/01_quickstart.ipynb --output-dir examples/
